# Generated by Django 3.2.7 on 2021-11-20 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podstawa_prawna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podstawa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Powiaty_Wlkp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powiat', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Rodzaj_umowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodz_um', models.CharField(default='Czynsz', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Rodzaje_jednostek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Stan_umow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stan', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Umowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_umowy', models.DateField()),
                ('nr_umowy', models.CharField(blank=True, default='BRAK', max_length=20)),
                ('nazwa_uzyczajacego', models.CharField(max_length=30, null=True)),
                ('adres_uzyczajacego', models.CharField(max_length=30, null=True)),
                ('kod_pocztowy_uzyczajacego', models.CharField(max_length=6, null=True)),
                ('miasto_uzyczajacego', models.CharField(max_length=20, null=True)),
                ('okres_obowiazywania', models.DateField(blank=True, default='')),
                ('pow_uzyczona', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rodzaj_kosztow_prad', models.BooleanField()),
                ('informacje_prad', models.TextField(blank=True, default='')),
                ('rodzaj_kosztow_gaz', models.BooleanField()),
                ('informacje_gaz', models.TextField(blank=True, default='')),
                ('rodzaj_kosztow_woda', models.BooleanField()),
                ('informacje_woda', models.TextField(blank=True, default='')),
                ('rodzaj_kosztow_co', models.BooleanField()),
                ('informacje_co', models.TextField(blank=True, default='')),
                ('adres_jedn', models.CharField(max_length=30, null=True)),
                ('miasto_jedn', models.CharField(max_length=20, null=True)),
                ('kod_pocztowy_jedn', models.CharField(max_length=6, null=True)),
                ('skan_umowy', models.FileField(blank=True, null=True, upload_to='umowy_pdf')),
                ('uwagi', models.TextField(blank=True, default='')),
                ('deleted', models.BooleanField(default=0)),
                ('utworzenie', models.DateTimeField(auto_now_add=True)),
                ('zmiana', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('podstawa_prawna', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.podstawa_prawna')),
                ('powiaty_jedn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowyapp.powiaty_wlkp')),
                ('rodzaj_jedn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowyapp.rodzaje_jednostek')),
                ('stan_umowy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.stan_umow')),
                ('typ_umowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowyapp.rodzaj_umowy')),
            ],
        ),
        migrations.CreateModel(
            name='Aneks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aneks', models.FileField(blank=True, null=True, upload_to='aneksy_pdf')),
                ('data_aneksu', models.DateField(null=True)),
                ('utworzenie', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('umowa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowyapp.umowa')),
            ],
        ),
    ]
