# Generated by Django 3.2.7 on 2021-09-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umowy',
            name='nr_umowy',
        ),
        migrations.AddField(
            model_name='umowy',
            name='adres',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='informacje',
            field=models.TextField(default='---Wpisz niezbędne informacje---'),
        ),
        migrations.AddField(
            model_name='umowy',
            name='kod_pocztowy',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='miasto',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='nazwa_uzyczajacego',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='okres_obowiazywania',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='pow_uzyczona',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='skan_umowy',
            field=models.FileField(blank=True, null=True, upload_to='umowy_pdf'),
        ),
        migrations.AddField(
            model_name='umowy',
            name='stan_umowy',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
