# Generated by Django 3.2.7 on 2021-09-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powiaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powiat', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rodzaj_jednostek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='umowy',
            name='adres_jedn',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='adres_uzyczajacego',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='umowy',
            name='informacje',
            field=models.TextField(default='---Niezbędne informacje---'),
        ),
        migrations.AddField(
            model_name='umowy',
            name='kod_pocztowy_jedn',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='kod_pocztowy_uzyczajacego',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='miasto_jedn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='miasto_uzyczajacego',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='nazwa_uzyczajacego',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='okres_obowiazywania',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='pow_uzyczona',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='rodzaj_kosztow_prad',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='umowy',
            name='skan_umowy',
            field=models.FileField(blank=True, null=True, upload_to='umowy_pdf'),
        ),
        migrations.AddField(
            model_name='umowy',
            name='stan_umowy',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='nr_umowy',
            field=models.CharField(default='BRAK', max_length=15),
        ),
    ]
