# Generated by Django 3.2.7 on 2021-10-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='pow_uzyczona',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='stan_umowy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.stan_umow'),
        ),
    ]
