# Generated by Django 3.2.8 on 2021-10-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umowy',
            name='podstawa_prawna',
        ),
    ]
