# Generated by Django 3.2.7 on 2021-11-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='termin_platnosci',
            field=models.CharField(blank=True, default='aa', max_length=100),
        ),
    ]
