# Generated by Django 3.2.7 on 2021-10-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0002_auto_20210926_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiaty_wlkp',
            name='powiat',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rodzaje_jednostek',
            name='rodzaj',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stan_umow',
            name='stan',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='data_umowy',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='nr_umowy',
            field=models.CharField(default='BRAK', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='okres_obowiazywania',
            field=models.DateField(blank=True, default=''),
        ),
    ]
