# Generated by Django 3.2.7 on 2021-10-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0002_auto_20211018_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='informacje_co',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='informacje_gaz',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='informacje_prad',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='informacje_woda',
            field=models.TextField(blank=True, default=''),
        ),
    ]
