# Generated by Django 3.2.8 on 2021-10-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0002_auto_20211008_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='informacje_co',
            field=models.TextField(default='---Niezbędne informacje---', null=True),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='informacje_gaz',
            field=models.TextField(default='---Niezbędne informacje---', null=True),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='informacje_prad',
            field=models.TextField(default='---Niezbędne informacje---', null=True),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='informacje_woda',
            field=models.TextField(default='---Niezbędne informacje---', null=True),
        ),
    ]
