# Generated by Django 3.2.7 on 2021-09-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0002_auto_20210925_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='umowy',
            name='powiaty_jedn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='umowyapp.powiaty_wlkp'),
        ),
    ]
