# Generated by Django 3.2.7 on 2021-11-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0003_remove_umowa_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aneks',
            old_name='aneks',
            new_name='skan_aneksu',
        ),
    ]
