# Generated by Django 3.2.8 on 2021-10-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0003_auto_20211008_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_kosztow_co',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_kosztow_gaz',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_kosztow_prad',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_kosztow_woda',
            field=models.BooleanField(null=True),
        ),
    ]
