# Generated by Django 3.2.7 on 2021-11-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0003_alter_umowy_termin_platnosci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='podstawa_prawna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.podstawa_prawna'),
        ),
    ]
