# Generated by Django 3.2.7 on 2021-11-09 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0003_auto_20211019_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Umowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_umowy', models.DateField()),
                ('nr_umowy', models.CharField(default='BRAK', max_length=20, null=True)),
                ('nazwa_uzyczajacego', models.CharField(max_length=30, null=True)),
                ('adres_uzyczajacego', models.CharField(max_length=30, null=True)),
                ('kod_pocztowy_uzyczajacego', models.CharField(max_length=6, null=True)),
                ('miasto_uzyczajacego', models.CharField(max_length=20, null=True)),
                ('okres_obowiazywania', models.DateField(blank=True, default='')),
                ('pow_uzyczona', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rodzaj_kosztow_prad', models.BooleanField()),
                ('informacje_prad', models.TextField(blank=True, default='')),
                ('rodzaj_kosztow_gaz', models.BooleanField()),
                ('informacje_gaz', models.TextField(blank=True, default='')),
                ('rodzaj_kosztow_woda', models.BooleanField()),
                ('informacje_woda', models.TextField(blank=True, default='')),
                ('rodzaj_kosztow_co', models.BooleanField()),
                ('informacje_co', models.TextField(blank=True, default='')),
                ('adres_jedn', models.CharField(max_length=30, null=True)),
                ('miasto_jedn', models.CharField(max_length=20, null=True)),
                ('kod_pocztowy_jedn', models.CharField(max_length=6, null=True)),
                ('skan_umowy', models.FileField(blank=True, null=True, upload_to='umowy_pdf')),
                ('uwagi', models.TextField(blank=True, default='')),
                ('deleted', models.BooleanField(default=0)),
                ('podstawa_prawna', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.podstawa_prawna')),
                ('powiaty_jedn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowyapp.powiaty_wlkp')),
                ('rodzaj_jedn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowyapp.rodzaje_jednostek')),
                ('stan_umowy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.stan_umow')),
                ('typ_umowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowyapp.rodzaj_umowy')),
            ],
        ),
        migrations.AlterField(
            model_name='aneksy',
            name='umowa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowyapp.umowa'),
        ),
        migrations.DeleteModel(
            name='Umowy',
        ),
    ]
