# Generated by Django 3.2.7 on 2021-09-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0003_umowy_powiaty_jedn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='powiaty_jedn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.powiaty_wlkp'),
        ),
    ]
