# Generated by Django 3.2.8 on 2021-10-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0003_umowy_podstawa_prawna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='uwagi',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
