# Generated by Django 3.2.8 on 2021-10-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0004_alter_umowy_uwagi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aneksy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aneks', models.FileField(blank=True, null=True, upload_to='aneksy_pdf')),
            ],
        ),
    ]
