# Generated by Django 3.2.8 on 2021-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0004_auto_20211008_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_kosztow_co',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_kosztow_gaz',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_kosztow_prad',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_kosztow_woda',
            field=models.BooleanField(),
        ),
    ]
