# Generated by Django 3.2.7 on 2021-11-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0004_rename_aneks_aneks_skan_aneksu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowa',
            name='nr_umowy',
            field=models.CharField(blank=True, default='(BRAK NUMERU)', max_length=20),
        ),
    ]
