# Generated by Django 3.2.7 on 2021-09-25 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0005_umowy_rodzaj_jedn'),
    ]

    operations = [
        migrations.AddField(
            model_name='umowy',
            name='stan_umowy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.stan_umow'),
        ),
    ]
