# Generated by Django 3.2.7 on 2021-11-11 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0005_umowa_modyfikowany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umowa',
            old_name='modyfikowany',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='umowa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
