# Generated by Django 3.2.8 on 2021-10-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0005_aneksy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aneksy',
            name='umowa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.umowy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_jedn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.rodzaje_jednostek'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='umowy',
            name='stan_umowy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.stan_umow'),
            preserve_default=False,
        ),
    ]
