# Generated by Django 3.2.7 on 2021-09-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0006_umowy_stan_umowy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_kosztow_prad',
            field=models.BooleanField(null=True),
        ),
    ]
