# Generated by Django 3.2.7 on 2021-10-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0006_auto_20211013_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='uwagi',
            field=models.TextField(default='Wpisz niezbędne informacje dotycace umowy', null=True),
        ),
    ]
