# Generated by Django 3.2.9 on 2021-11-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0006_auto_20211111_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowa',
            name='nr_umowy',
            field=models.CharField(blank=True, default='BRAK', max_length=20),
        ),
    ]
