# Generated by Django 3.2.9 on 2021-11-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0007_rename_deleted_umowa_archiwum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umowa',
            name='autor',
        ),
    ]
