# Generated by Django 3.2.7 on 2021-09-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0007_alter_umowy_rodzaj_kosztow_prad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='rodzaj_kosztow_prad',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
