# Generated by Django 3.2.7 on 2021-11-20 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umowyapp', '0007_alter_umowa_nr_umowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='umowa',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
