# Generated by Django 3.2.7 on 2021-09-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0008_alter_umowy_rodzaj_kosztow_prad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodzaj_umowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodz_um', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='umowy',
            name='powiaty_jedn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.powiaty_wlkp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='umowy',
            name='typ_umowy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umowyapp.rodzaj_umowy'),
        ),
    ]
