# Generated by Django 3.2.7 on 2021-10-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0008_alter_umowy_uwagi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowy',
            name='uwagi',
            field=models.TextField(default='Wpisz niezbędne informacje dotyczące umowy'),
        ),
    ]
