# Generated by Django 3.2.7 on 2021-09-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0009_auto_20210926_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodzaj_umowy',
            name='rodz_um',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
