# Generated by Django 3.2.7 on 2021-10-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0009_alter_umowy_uwagi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodzaj_umowy',
            name='rodz_um',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
