# Generated by Django 3.2.9 on 2021-11-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowyapp', '0009_umowa_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aneks',
            old_name='umowa',
            new_name='umowa_id',
        ),
        migrations.AlterField(
            model_name='aneks',
            name='skan_aneksu',
            field=models.FileField(blank=True, null=True, upload_to='aneksy_pdf/%Y'),
        ),
    ]
